name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: C++, FFTW ${{ matrix.fftw }}
    strategy:
      matrix:
        fftw: ["ON", "OFF"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential \
          libboost-dev libeigen3-dev libfftw3-dev

    - name: Build and install segyio
      run: |
        git clone --branch v1.9.12 https://github.com/equinor/segyio.git
        cd segyio
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_PYTHON=OFF -DEXPERIMENTAL=ON -DBUILD_TESTING=OFF -DBUILD_BIN=OFF
        make
        sudo make install

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Python dependencies
      run: pip install 'segyio==1.9.13'

    - name: Build and test
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ctest --output-on-failure
        make diff

  build-python:
    name: Python bindings, FFTW ${{ matrix.fftw }}
    strategy:
      matrix:
        fftw: ["ON", "OFF"]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential \
          libboost-dev libeigen3-dev libfftw3-dev

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Python dependencies
      run: pip install pybind11 pytest xtgeo

    - name: Build and test
      run: |
        pip install \
          -Ccmake.define.CMAKE_PREFIX_PATH="$(pybind11-config --cmakedir)" \
          -Ccmake.define.CMAKE_BUILD_TYPE=Debug \
          -Ccmake.define.USE_FFTW=${{ matrix.fftw }} \
          python/ --verbose
        cd python
        python -m pytest tests/
