name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: C++, FFTW ${{ matrix.fftw }}
    strategy:
      matrix:
        fftw: ["ON", "OFF"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential \
          libboost-dev libeigen3-dev libfftw3-dev

    - name: Build and install cppcheck
      run: |
        git clone https://github.com/danmar/cppcheck.git cppcheck-src
        mkdir cppcheck-build && cd cppcheck-build
        cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_CXX_FLAGS="-w" \
              ../cppcheck-src
        make
        sudo make install
        cd ..

    - name: Build and install segyio
      run: |
        git clone --branch v1.9.12 https://github.com/equinor/segyio.git
        cd segyio
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_PYTHON=OFF -DEXPERIMENTAL=ON -DBUILD_TESTING=OFF -DBUILD_BIN=OFF
        make
        sudo make install

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Python dependencies
      run: pip install 'segyio==1.9.13' pybind11

    - name: Build and test
      run: |
        mkdir build
        cd build
        cmake -DBUILD_SHARED_LIBS=OFF \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
              -DSI4TI_PYTHON_BINDINGS=ON \
              -DCMAKE_PREFIX_PATH="$(pybind11-config --cmakedir)" \
              ..
        make
        ctest --output-on-failure
        make diff

    - name: Run cppcheck
      working-directory: build
      # TODO: Fix errors to make this test fail on error
      continue-on-error: true
      run: |
        cppcheck --enable=style,portability,performance,warning \
                 --library=posix \
                 --inline-suppr \
                 --project=compile_commands.json \
                 --error-exitcode=1 \
                 --suppressions-list=../cppcheck/suppressions.txt \
                 --verbose \
                 --template="{file}:{line} [{severity}] {message}" \
                 2>&1

  build-python:
    name: Python bindings, FFTW ${{ matrix.fftw }}
    strategy:
      matrix:
        fftw: ["ON", "OFF"]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential \
          libeigen3-dev libfftw3-dev

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Python dependencies
      run: pip install pybind11 pytest xtgeo

    - name: Build and test
      run: |
        pip install \
          -Ccmake.define.CMAKE_PREFIX_PATH="$(pybind11-config --cmakedir)" \
          -Ccmake.define.CMAKE_BUILD_TYPE=Debug \
          -Ccmake.define.USE_FFTW=${{ matrix.fftw }} \
          . --verbose
        cd python
        python -m pytest tests/
