name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  segyio_version: '1.9.13'

jobs:
  build:
    name: C++, FFTW ${{ matrix.fftw }}
    strategy:
      matrix:
        fftw: ["ON", "OFF"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential \
          libboost-dev libeigen3-dev libfftw3-dev

    # This installation of segyio is used to generate the experimental C++
    # headers needed to build si4ti. The Python interface is not build to
    # simplify the build prcoess. The Python interface is instead installed via
    # pip (see below).
    - name: Build and install segyio
      run: |
        git clone --branch "v${{ env.segyio_version }}" https://github.com/equinor/segyio.git
        cd segyio
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_SHARED_LIBS=ON \
          -DBUILD_PYTHON=OFF \
          -DEXPERIMENTAL=ON \
          -DBUILD_TESTING=OFF \
          -DBUILD_BIN=OFF
        make -j
        sudo make install

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    # This installation of segyio is used within the tests run by `make diff`.
    - name: Install Python dependencies for tests
      run: pip install "segyio==${{ env.segyio_version }}"

    - name: Build and test
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release \
              -DUSE_FFTW=${{ matrix.fftw }} \
              ..
        make -j
        ctest --output-on-failure
        make diff
