name: Build and Test Python bindings
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential \
          libboost-dev libeigen3-dev libfftw3-dev

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: pip install 'segyio==1.9.13' pybind11 pytest

    - name: Build and test
      run: |
        cd python
        pip install -Ccmake.define.CMAKE_PREFIX_PATH="$(pybind11-config --cmakedir)" \
          -Ccmake.define.CMAKE_BUILD_TYPE=Debug . --verbose
        python -m pytest tests
