name: Style checks
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    name: Style checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"
    - run: |
        pip install pre-commit
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit/
        key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - run:
        pre-commit run --all-files
