name: Style checks
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    name: Style checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"
    - run: |
        pip install pre-commit
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit/
        key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - run:
        pre-commit run --all-files

  cppcheck:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential \
          libboost-dev libeigen3-dev libfftw3-dev cppcheck

    - name: Build and install segyio
      run: |
        git clone --branch v1.9.12 https://github.com/equinor/segyio.git
        cd segyio
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_PYTHON=OFF -DEXPERIMENTAL=ON -DBUILD_TESTING=OFF -DBUILD_BIN=OFF
        make -j
        sudo make install

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"

    - name: Install Python dependencies
      run: pip install 'segyio==1.9.13' pybind11

    - name: Configure project
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
              -DBUILD_PYTHON=ON \
              -DUSE_FFTW=YES \
              -DCMAKE_PREFIX_PATH="$(pybind11-config --cmakedir)" \
              ..
        make -j

    - name: Run cppcheck
      working-directory: build
      # TODO: Fix errors to make this test fail on error
      run: |
        cppcheck --enable=style,portability,performance,warning \
                 --library=posix \
                 --inline-suppr \
                 --project=compile_commands.json \
                 --error-exitcode=1 \
                 --suppressions-list=../cppcheck/suppressions.txt \
                 --verbose \
                 --template="{file}:{line} [{severity}] {message}"
